In [4]:
import pandas as pd
import pymysql.cursors
import pymysql

In [5]:
# Conexión a mi base de datos
connection = pymysql.connect(
    host='127.0.0.1',
    user='root',
    password='carla123',
    db='datawarehouse',
    charset='utf8mb4',
    cursorclass=pymysql.cursors.DictCursor
)

# Consulta SQL
sql = 'SELECT * FROM labevents'

# Creo un dataframe a partir de los datos de la tabla
labevents= pd.read_sql(sql, connection)

# Cierro la conexión
connection.close()

#Muestro mi dataframe
labevents.head()

/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(


row_id  SUBJECT_ID  HADM_ID  ITEMID           CHARTTIME VALUE  VALUENUM  \
0  19931749       40124   126179   50868 2130-02-04 00:35:00    20      20.0   
1  19931750       40124   126179   50882 2130-02-04 00:35:00    24      24.0   
2  19931751       40124   126179   50893 2130-02-04 00:35:00    88       8.8   
3  19931752       40124   126179   50902 2130-02-04 00:35:00   101     101.0   
4  19931753       40124   126179   50910 2130-02-04 00:35:00   129     129.0   

  VALUEUOM FLAG  
0     mEqL  nan  
1     mEqL  nan  
2     mgdL  nan  
3     mEqL  nan  
4      IUL  nan

In [6]:
labevents.columns= labevents.columns.str.lower()

In [7]:
labevents.head()

row_id  subject_id  hadm_id  itemid           charttime value  valuenum  \
0  19931749       40124   126179   50868 2130-02-04 00:35:00    20      20.0   
1  19931750       40124   126179   50882 2130-02-04 00:35:00    24      24.0   
2  19931751       40124   126179   50893 2130-02-04 00:35:00    88       8.8   
3  19931752       40124   126179   50902 2130-02-04 00:35:00   101     101.0   
4  19931753       40124   126179   50910 2130-02-04 00:35:00   129     129.0   

  valueuom flag  
0     mEqL  nan  
1     mEqL  nan  
2     mgdL  nan  
3     mEqL  nan  
4      IUL  nan

In [8]:
diccionario = pd.read_csv("dataset/D_LABITEMS.csv")
diccionario.head()

row_id  itemid                                label  fluid   category  \
0       1   50800                        SPECIMEN TYPE  BLOOD  BLOOD GAS   
1       2   50801           Alveolar-arterial Gradient  Blood  Blood Gas   
2       3   50802                          Base Excess  Blood  Blood Gas   
3       4   50803  Calculated Bicarbonate, Whole Blood  Blood  Blood Gas   
4       5   50804                 Calculated Total CO2  Blood  Blood Gas   

  loinc_code  
0        NaN  
1    19991-9  
2    11555-0  
3     1959-6  
4    34728-6

In [9]:
diccionario= diccionario.drop(['row_id', 'fluid', 'category', 'loinc_code'], axis=1)

In [10]:
labevents = pd.merge(labevents, diccionario, on= 'itemid') 

In [11]:
labevents.head()

row_id  subject_id  hadm_id  itemid           charttime value  valuenum  \
0  19931749       40124   126179   50868 2130-02-04 00:35:00    20      20.0   
1  19931801       40124   126179   50868 2130-02-04 06:44:00    17      17.0   
2  19931853       40124   126179   50868 2130-02-05 05:57:00    15      15.0   
3  19931909       40124   126179   50868 2130-02-06 05:19:00    13      13.0   
4  19931937       40124   126179   50868 2130-02-07 06:40:00    12      12.0   

  valueuom flag      label  
0     mEqL  nan  Anion Gap  
1     mEqL  nan  Anion Gap  
2     mEqL  nan  Anion Gap  
3     mEqL  nan  Anion Gap  
4     mEqL  nan  Anion Gap

In [12]:
labevents.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76074 entries, 0 to 76073
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   row_id      76074 non-null  object        
 1   subject_id  76074 non-null  int64         
 2   hadm_id     76074 non-null  int64         
 3   itemid      76074 non-null  int64         
 4   charttime   76074 non-null  datetime64[ns]
 5   value       76074 non-null  object        
 6   valuenum    76074 non-null  float64       
 7   valueuom    76074 non-null  object        
 8   flag        76074 non-null  object        
 9   label       76074 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(3), object(5)
memory usage: 6.4+ MB


In [13]:
labevents['itemid'].unique()

array([50868, 50882, 50893, 50902, 50910, 50911, 50912, 50920, 50931,
       50960, 50970, 50971, 50983, 51003, 51006, 51146, 51200, 51221,
       51222, 51237, 51244, 51248, 51249, 51250, 51254, 51256, 51265,
       51274, 51275, 51277, 51279, 51301, 50805, 50813, 50814, 50817,
       50800, 50801, 50802, 50804, 50812, 50816, 50818, 50819, 50820,
       50821, 50823, 50826, 50827, 50861, 50862, 50863, 50878, 50885,
       50954, 50828, 50887, 50915, 50993, 51010, 51463, 51464, 51466,
       51476, 51478, 51484, 51486, 51487, 51491, 51492, 51493, 51498,
       51506, 51508, 51512, 51514, 51516, 51519, 50815, 50825, 50930,
       50976, 50995, 51001, 51082, 51087, 51100, 51474, 50924, 50952,
       50953, 50998, 51046, 51053, 51054, 51059, 51444, 51446, 51447,
       51450, 51453, 51455, 51457, 51458, 50883, 50884, 51284, 50867,
       50935, 50937, 50940, 50942, 50943, 50956, 51214, 51283, 51460,
       50822, 50824, 51078, 51097, 51104, 50908, 51137, 51143, 51144,
       51151, 51233,

In [14]:
#Creo una lista con los labs que necesito para mi modelo de ML
analisis_ml = [50821, 51265, 50885, 220052, 198, 50912, 40055, 618, 855, 220050, 211, 51, 223761, 3395, 40055, 51006, 51300, 50822, 50824, 50882, 50885]

In [15]:
# creamos un nuevo DataFrame que contenga solo las filas que contienen elementos de la lista
labevents_ml = labevents[labevents['itemid'].isin(analisis_ml)]

In [16]:
labevents_ml.head()

row_id  subject_id  hadm_id  itemid           charttime value  \
2134  19931750       40124   126179   50882 2130-02-04 00:35:00    24   
2135  19931803       40124   126179   50882 2130-02-04 06:44:00    27   
2136  19931854       40124   126179   50882 2130-02-05 05:57:00    26   
2137  19931910       40124   126179   50882 2130-02-06 05:19:00    26   
2138  19931938       40124   126179   50882 2130-02-07 06:40:00    28   

      valuenum valueuom flag        label  
2134      24.0     mEqL  nan  Bicarbonate  
2135      27.0     mEqL  nan  Bicarbonate  
2136      26.0     mEqL  nan  Bicarbonate  
2137      26.0     mEqL  nan  Bicarbonate  
2138      28.0     mEqL  nan  Bicarbonate

In [17]:
labevents['subject_id'].unique()

array([40124, 40177, 40204, 40277, 40286, 40304, 40310, 40456, 40503,
       40595, 40601, 40612, 40655, 40687, 41795, 41914, 41976, 41983,
       42033, 42066, 42075, 42135, 42199, 42231, 42275, 42281, 42292,
       42302, 42321, 42346, 42367, 42412, 42430, 42458, 43735, 43746,
       43748, 43779, 43798, 43827, 43870, 43879, 43881, 43909, 43927,
       44083, 44154, 44212, 44222, 44228, 10006, 10011, 10013, 10017,
       10019, 10026, 10027, 10029, 10032, 10033, 10035, 10036, 10038,
       10040, 10042, 10043, 10044, 10045, 10046, 10056, 10059, 10061,
       10064, 10065, 10067, 10069, 10074, 10076, 10083, 10088, 10089,
       10090, 10093, 10094, 10098, 10101, 10102, 10104, 10106, 10111,
       10112, 10114, 10117, 10119, 10120, 10124, 10126, 10127, 10130,
       10132])

In [18]:
paciente = labevents_ml[labevents_ml['subject_id'] == 40124]  # Filtrar para solo incluir las filas del paciente 12345
analisis = paciente['label']  # Seleccionar la columna "label" para ver los nombres de los análisis realizados
print(analisis)



2134          Bicarbonate
2135          Bicarbonate
2136          Bicarbonate
2137          Bicarbonate
2138          Bicarbonate
               ...       
57367                 pO2
57368                 pO2
57369                 pO2
61310    Bilirubin, Total
61311    Bilirubin, Total
Name: label, Length: 69, dtype: object


Respiración PaO2/FiO2 (mmHg): chartevents.ITEMID = 50821, 51265, 50885, 220052, 198, 50912, 40055, 618, 855, 220050, 211, 51, 223761, 3395, 40055, 51006, 51300, 50822, 50824, 50882, 50885
Coagulación (Plaquetas): chartevents.ITEMID = 51265
Hígado (Bilirrubina mg/dL): labevents.ITEMID = 50885
Cardiovascular (PAM o su manejo): chartevents.ITEMID = 220052
Sistema Nervioso Central (Escala de coma de Glasgow): chartevents.ITEMID = 198
Renal (Creatinina mL/dL y Gasto urinario mL/día): chartevents.ITEMID = 50912 y outputevents.ITEMID = 40055
Para qSOFA, los códigos de las variables en MIMIC-III serían los siguientes:

Frecuencia respiratoria >= 22 resp/min: chartevents.ITEMID = 618
Alteración del sensorio: carevue.ITEMID = 448 (enfermería) o carevue.ITEMID = 855 (médico)
Presión arterial sistólica <= 100 mmHg: chartevents.ITEMID = 220050
Por último, para el Sistema Simplificado de Evaluación Pronóstica (SAPS-II), los códigos de las variables en MIMIC-III serían los siguientes:

HR: chartevents.ITEMID = 211
SBP: chartevents.ITEMID = 51
TEMP: chartevents.ITEMID = 223761
PAO2/FIO2: chartevents.ITEMID = 3395
UO (mL): outputevents.ITEMID = 40055
S. UREA: labevents.ITEMID = 51006
TLC: labevents.ITEMID = 51300
K: labevents.ITEMID = 50822
Na: labevents.ITEMID = 50824
BICARBONATO: labevents.ITEMID = 50882
BIL: labevents.ITEMID = 50885
GCS: carevue.ITEMID = 198 (coma de Glasgow)

In [19]:
labevents_ml.to_csv('labevents_ml.csv', index=False)
